---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  namespace: micro-app
  labels:
    app: product-app

spec:
  replicas: 1
  selector:
    matchLabels: 
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec: 
     containers:
       - name: product-catalouge
         image: vibhutijain12/k8s-catalogue
         ports:
         - containerPort: 8020
         livenessProbe:
           httpGet:
             path: /healthcheck 
             port: 8025
           initialDelaySeconds: 30
           timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  namespace: micro-app

spec:
  type: NodePort
  selector:
    app: product-app
  ports: 
    - protocol: TCP 
      port: 8020
      targetPort: 8020
      name: http
