---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deploy
  namespace: micro-app
  labels:
    app: stock-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
     containers:
       - name: stock-manager
         image: vibhutijain12/k8s-stockmgm
         ports:
         - containerPort: 8030
         livenessProbe:
           httpGet:
             path: /actuator/health
             port: 8030
           initialDelaySeconds: 30
           timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: micro-app

spec:
  type: NodePort
  selector:
    app: stock-app
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 8030
      name: http
